import Script from "next/script"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import script from 'next/script'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>Chating</title>
      <Script src="https://developers.kakao.com/sdk/js/kakao.js" async />
      <body>{children}</body>
    </html>
  )
}
